# Generated by Django 5.0.6 on 2024-07-27 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('alternative_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('governorate', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
